language: go

go:
    - "1.15"

branches:
  only:
    - master

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get -t -v ./...

before_script:
  - go vet *.go

script:
  - "TEST_DATA_PATH=./test/data.json go test -v ./..."
  - "go test -v -covermode=count -coverprofile=coverage.out"
  - "$GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci"
